import { format, addDays, startOfMonth } from "date-fns";
import type { AcademicEvent } from "./types";

const today = new Date();
const som = startOfMonth(today);

const d = (offset: number) => format(addDays(som, offset), "yyyy-MM-dd");

export const MOCK_EVENTS: AcademicEvent[] = [
  {
    id: "e1",
    title: "Data Structures Lecture",
    description: "Trees and graph traversal algorithms with hands-on examples.",
    date: d(2),
    startTime: "09:00",
    endTime: "10:30",
    venue: "Room 204, Block A",
    department: "CSE",
    year: "II",
    section: "A",
    category: "lecture",
  },
  {
    id: "e2",
    title: "Mid-Semester Examination",
    description: "Digital electronics mid-term. Bring calculators. No mobile phones allowed.",
    date: d(5),
    startTime: "10:00",
    endTime: "13:00",
    venue: "Central Exam Hall",
    department: "ECE",
    year: "III",
    section: "B",
    category: "exam",
  },
  {
    id: "e3",
    title: "TechFest 2026",
    description: "Annual technology festival featuring hackathons, workshops and guest talks.",
    date: d(8),
    startTime: "09:00",
    endTime: "17:00",
    venue: "Main Auditorium",
    department: "CSE",
    year: "III",
    section: "A",
    category: "event",
  },
  {
    id: "e4",
    title: "Department Meeting",
    description: "Faculty review and curriculum planning session.",
    date: d(8),
    startTime: "14:00",
    endTime: "16:00",
    venue: "Conference Room 3",
    department: "MECH",
    year: "IV",
    section: "A",
    category: "meeting",
  },
  {
    id: "e5",
    title: "Republic Day",
    description: "National holiday. Institution closed.",
    date: d(12),
    startTime: "00:00",
    endTime: "23:59",
    venue: "—",
    department: "CSE",
    year: "I",
    section: "A",
    category: "holiday",
  },
  {
    id: "e6",
    title: "AI Workshop",
    description: "Hands-on workshop on modern LLMs and prompt engineering.",
    date: d(15),
    startTime: "10:00",
    endTime: "15:00",
    venue: "AI Lab, Block C",
    department: "IT",
    year: "III",
    section: "A",
    category: "workshop",
  },
  {
    id: "e7",
    title: "Signals & Systems",
    description: "Fourier transforms — continued from previous lecture.",
    date: d(15),
    startTime: "11:00",
    endTime: "12:30",
    venue: "Room 108",
    department: "ECE",
    year: "II",
    section: "A",
    category: "lecture",
  },
  {
    id: "e8",
    title: "Structural Analysis",
    description: "Beam deflection problem solving.",
    date: d(18),
    startTime: "09:00",
    endTime: "10:30",
    venue: "Room 305, Block B",
    department: "CIVIL",
    year: "III",
    section: "B",
    category: "lecture",
  },
  {
    id: "e9",
    title: "Power Systems Lab",
    description: "Lab session on transformer testing.",
    date: d(20),
    startTime: "14:00",
    endTime: "17:00",
    venue: "EEE Lab 2",
    department: "EEE",
    year: "III",
    section: "A",
    category: "lecture",
  },
  {
    id: "e10",
    title: "Final Project Presentations",
    description: "Fourth-year capstone project demos in front of the review panel.",
    date: d(22),
    startTime: "10:00",
    endTime: "16:00",
    venue: "Seminar Hall 1",
    department: "CSE",
    year: "IV",
    section: "A",
    category: "event",
  },
  {
    id: "e11",
    title: "Semester End Exam",
    description: "Operating Systems final exam.",
    date: d(25),
    startTime: "09:30",
    endTime: "12:30",
    venue: "Central Exam Hall",
    department: "CSE",
    year: "II",
    section: "A",
    category: "exam",
  },
  {
    id: "e12",
    title: "Guest Lecture: Robotics",
    description: "Industry expert talk on the future of collaborative robotics.",
    date: d(28),
    startTime: "15:00",
    endTime: "16:30",
    venue: "Auditorium 2",
    department: "MECH",
    year: "III",
    section: "A",
    category: "workshop",
  },
];